epopee_homepage:
    path:     /
    defaults: { _controller: EpopeeBundle:Default:index }

epopee_auto:
    path:     /auto/{auto}
    defaults: { _controller: EpopeeBundle:Default:auto }

epopee_reflection_add:
    path:     /reflection/add
    defaults: { _controller: EpopeeBundle:Reflection:add }

epopee_reflection_index:
    path:     /reflection
    defaults: { _controller: EpopeeBundle:Reflection:index }